blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Dokumentation
    url: https://github.com/public-ui/.github
    about: Durchsuchen Sie die Dokumentation fÃ¼r Antworten auf hÃ¤ufige Fragen
  - name: ğŸ’¬ Diskussionen
    url: https://github.com/public-ui/.github/discussions
    about: Stellen Sie Fragen und diskutieren Sie mit der Community
